import type { Listing, User, MarketPrice, WeatherData, CropAdvice, Conversation, Message, CropType } from '@/types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Jean Baptiste Nkurunziza',
    email: 'jean@example.com',
    phone: '+250 788 123 456',
    role: 'farmer',
    location: 'Musanze',
    verified: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Marie Claire Uwimana',
    email: 'marie@example.com',
    phone: '+250 788 234 567',
    role: 'farmer',
    location: 'Nyagatare',
    verified: true,
    createdAt: new Date('2024-02-20'),
  },
  {
    id: '3',
    name: 'Emmanuel Habimana',
    email: 'emmanuel@example.com',
    phone: '+250 788 345 678',
    role: 'buyer',
    location: 'Kigali',
    verified: true,
    createdAt: new Date('2024-03-10'),
  },
];

// Mock Listings
export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'Fresh Organic Tomatoes',
    cropType: 'tomatoes',
    quantity: 500,
    pricePerKg: 800,
    description: 'Freshly harvested organic tomatoes from our family farm in Musanze. No pesticides used, perfect for restaurants and markets.',
    location: 'Musanze, Northern Province',
    district: 'musanze',
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400'],
    sellerId: '1',
    seller: mockUsers[0],
    createdAt: new Date('2024-06-10'),
    coordinates: { lat: -1.4977, lng: 29.6346 },
  },
  {
    id: '2',
    title: 'Premium Arabica Coffee Beans',
    cropType: 'coffee',
    quantity: 200,
    pricePerKg: 3500,
    description: 'High-quality Arabica coffee beans grown at 1800m altitude. Washed process, sun-dried. Perfect for export or specialty roasters.',
    location: 'Huye, Southern Province',
    district: 'huye',
    images: ['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400'],
    sellerId: '2',
    seller: mockUsers[1],
    createdAt: new Date('2024-06-08'),
    coordinates: { lat: -2.5967, lng: 29.7394 },
  },
  {
    id: '3',
    title: 'Sweet Bananas (Igitoki)',
    cropType: 'bananas',
    quantity: 1000,
    pricePerKg: 350,
    description: 'Traditional Rwandan cooking bananas, locally known as Igitoki. Great for making Isombe and other traditional dishes.',
    location: 'Rwamagana, Eastern Province',
    district: 'rwamagana',
    images: ['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400'],
    sellerId: '1',
    seller: mockUsers[0],
    createdAt: new Date('2024-06-12'),
    coordinates: { lat: -1.9496, lng: 30.4344 },
  },
  {
    id: '4',
    title: 'Red Kidney Beans',
    cropType: 'beans',
    quantity: 800,
    pricePerKg: 950,
    description: 'High-quality red kidney beans, freshly harvested. Excellent for cooking, high protein content.',
    location: 'Nyagatare, Eastern Province',
    district: 'nyagatare',
    images: ['https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=400'],
    sellerId: '2',
    seller: mockUsers[1],
    createdAt: new Date('2024-06-11'),
    coordinates: { lat: -1.2976, lng: 30.3277 },
  },
  {
    id: '5',
    title: 'Irish Potatoes (Large)',
    cropType: 'potatoes',
    quantity: 2000,
    pricePerKg: 450,
    description: 'Large-sized Irish potatoes, perfect for restaurants and hotels. Consistent quality guaranteed.',
    location: 'Musanze, Northern Province',
    district: 'musanze',
    images: ['https://images.unsplash.com/photo-1518977676601-b53f82ber44e?w=400'],
    sellerId: '1',
    seller: mockUsers[0],
    createdAt: new Date('2024-06-09'),
    coordinates: { lat: -1.5016, lng: 29.6262 },
  },
  {
    id: '6',
    title: 'Fresh Carrots',
    cropType: 'carrots',
    quantity: 300,
    pricePerKg: 600,
    description: 'Fresh, sweet carrots perfect for cooking or juicing. Grown organically in volcanic soil.',
    location: 'Rubavu, Western Province',
    district: 'rubavu',
    images: ['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400'],
    sellerId: '2',
    seller: mockUsers[1],
    createdAt: new Date('2024-06-13'),
    coordinates: { lat: -1.6840, lng: 29.2585 },
  },
  {
    id: '7',
    title: 'Yellow Maize',
    cropType: 'maize',
    quantity: 5000,
    pricePerKg: 280,
    description: 'Bulk yellow maize suitable for animal feed or flour production. Dry, ready for storage.',
    location: 'Gatsibo, Eastern Province',
    district: 'gatsibo',
    images: ['https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400'],
    sellerId: '1',
    seller: mockUsers[0],
    createdAt: new Date('2024-06-07'),
    coordinates: { lat: -1.5860, lng: 30.4589 },
  },
  {
    id: '8',
    title: 'Green Cabbage',
    cropType: 'cabbage',
    quantity: 400,
    pricePerKg: 300,
    description: 'Fresh green cabbage heads, tightly packed. Ideal for restaurants and vegetable vendors.',
    location: 'Bugesera, Eastern Province',
    district: 'bugesera',
    images: ['https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=400'],
    sellerId: '2',
    seller: mockUsers[1],
    createdAt: new Date('2024-06-14'),
    coordinates: { lat: -2.1557, lng: 30.0324 },
  },
];

// Mock Market Prices
export const mockMarketPrices: MarketPrice[] = [
  { cropType: 'tomatoes', price: 800, change: 50, changePercent: 6.7, updatedAt: new Date() },
  { cropType: 'beans', price: 950, change: -30, changePercent: -3.1, updatedAt: new Date() },
  { cropType: 'maize', price: 280, change: 10, changePercent: 3.7, updatedAt: new Date() },
  { cropType: 'potatoes', price: 450, change: 0, changePercent: 0, updatedAt: new Date() },
  { cropType: 'bananas', price: 350, change: 25, changePercent: 7.7, updatedAt: new Date() },
  { cropType: 'coffee', price: 3500, change: 200, changePercent: 6.1, updatedAt: new Date() },
  { cropType: 'rice', price: 1200, change: -50, changePercent: -4.0, updatedAt: new Date() },
  { cropType: 'carrots', price: 600, change: 15, changePercent: 2.6, updatedAt: new Date() },
  { cropType: 'cabbage', price: 300, change: -10, changePercent: -3.2, updatedAt: new Date() },
  { cropType: 'onions', price: 700, change: 30, changePercent: 4.5, updatedAt: new Date() },
];

// Mock Weather
export const mockWeather: WeatherData = {
  location: 'Kigali',
  temperature: 24,
  condition: 'Partly Cloudy',
  humidity: 65,
  windSpeed: 12,
  forecast: [
    { date: new Date(), high: 26, low: 18, condition: 'Sunny' },
    { date: new Date(Date.now() + 86400000), high: 25, low: 17, condition: 'Partly Cloudy' },
    { date: new Date(Date.now() + 172800000), high: 24, low: 16, condition: 'Rain' },
    { date: new Date(Date.now() + 259200000), high: 23, low: 15, condition: 'Rain' },
    { date: new Date(Date.now() + 345600000), high: 25, low: 17, condition: 'Sunny' },
  ],
};

// Mock Crop Advice
export const mockCropAdvice: CropAdvice[] = [
  {
    id: '1',
    cropType: 'tomatoes',
    title: 'Best Time to Plant Tomatoes',
    content: 'In Rwanda, the best time to plant tomatoes is at the beginning of the rainy season (March-May and September-November). Ensure proper spacing of 60cm between plants for optimal growth.',
    category: 'planting',
    createdAt: new Date('2024-06-01'),
  },
  {
    id: '2',
    cropType: 'beans',
    title: 'Managing Bean Fly Infestation',
    content: 'Bean fly is a major pest affecting beans in Rwanda. Apply neem-based pesticides early in the morning. Practice crop rotation to reduce pest pressure.',
    category: 'pest_control',
    createdAt: new Date('2024-06-02'),
  },
  {
    id: '3',
    cropType: 'coffee',
    title: 'Coffee Harvesting Tips',
    content: 'Only harvest cherries that are fully red for best quality. Pick every 10-14 days during peak season. Process within 24 hours of harvesting.',
    category: 'harvest',
    createdAt: new Date('2024-06-03'),
  },
  {
    id: '4',
    cropType: 'maize',
    title: 'Optimal Fertilizer Application',
    content: 'Apply DAP fertilizer at planting (50kg/ha) and urea as top dressing 4-6 weeks after germination. Avoid fertilizer contact with stems.',
    category: 'care',
    createdAt: new Date('2024-06-04'),
  },
  {
    id: '5',
    cropType: 'potatoes',
    title: 'Preventing Potato Blight',
    content: 'Monitor plants closely during humid conditions. Apply fungicides preventively before symptoms appear. Remove and destroy infected plants immediately.',
    category: 'pest_control',
    createdAt: new Date('2024-06-05'),
  },
];

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    id: '1',
    participants: [mockUsers[0], mockUsers[2]],
    lastMessage: {
      id: '1',
      senderId: '3',
      receiverId: '1',
      content: 'Hello, I\'m interested in your tomatoes. Are they still available?',
      createdAt: new Date(Date.now() - 3600000),
      read: false,
    },
    unreadCount: 1,
  },
  {
    id: '2',
    participants: [mockUsers[1], mockUsers[2]],
    lastMessage: {
      id: '2',
      senderId: '2',
      receiverId: '3',
      content: 'Yes, I can deliver to Kigali. The transport cost will be 50 RWF/kg.',
      createdAt: new Date(Date.now() - 7200000),
      read: true,
    },
    unreadCount: 0,
  },
];

// Mock Messages for a conversation
export const mockMessages: Message[] = [
  {
    id: '1',
    senderId: '3',
    receiverId: '1',
    content: 'Hello, I saw your listing for organic tomatoes. Are they still available?',
    createdAt: new Date(Date.now() - 7200000),
    read: true,
  },
  {
    id: '2',
    senderId: '1',
    receiverId: '3',
    content: 'Yes! I have about 500kg available. Fresh from this week\'s harvest.',
    createdAt: new Date(Date.now() - 6800000),
    read: true,
  },
  {
    id: '3',
    senderId: '3',
    receiverId: '1',
    content: 'Great! What\'s your best price for 100kg?',
    createdAt: new Date(Date.now() - 6400000),
    read: true,
  },
  {
    id: '4',
    senderId: '1',
    receiverId: '3',
    content: 'For 100kg, I can do 750 RWF/kg. That\'s 75,000 RWF total.',
    createdAt: new Date(Date.now() - 6000000),
    read: true,
  },
  {
    id: '5',
    senderId: '3',
    receiverId: '1',
    content: 'Can you deliver to Kigali?',
    createdAt: new Date(Date.now() - 5600000),
    read: true,
  },
  {
    id: '6',
    senderId: '1',
    receiverId: '3',
    content: 'Yes, delivery is available. It will cost an additional 5,000 RWF for Kigali.',
    createdAt: new Date(Date.now() - 3600000),
    read: false,
  },
];

// Crop type labels
export const cropTypeLabels: Record<CropType, { en: string; rw: string }> = {
  maize: { en: 'Maize', rw: 'Ibigori' },
  beans: { en: 'Beans', rw: 'Ibishyimbo' },
  rice: { en: 'Rice', rw: 'Umuceri' },
  cassava: { en: 'Cassava', rw: 'Imyumbati' },
  potatoes: { en: 'Potatoes', rw: 'Ibirayi' },
  sweet_potatoes: { en: 'Sweet Potatoes', rw: 'Ibijumba' },
  bananas: { en: 'Bananas', rw: 'Ibitoki' },
  tomatoes: { en: 'Tomatoes', rw: 'Inyanya' },
  onions: { en: 'Onions', rw: 'Ibitunguru' },
  cabbage: { en: 'Cabbage', rw: 'Amashu' },
  carrots: { en: 'Carrots', rw: 'Karoti' },
  coffee: { en: 'Coffee', rw: 'Ikawa' },
  tea: { en: 'Tea', rw: 'Icyayi' },
  sorghum: { en: 'Sorghum', rw: 'Amasaka' },
  wheat: { en: 'Wheat', rw: 'Ingano' },
};
